import type { LevelMeta } from "../level";
import type { EditorModel } from "./model";

// The export const name a level file declares, derived from the file/level
// name. `levelN` maps to LEVEL_N (matching the hand-authored built-ins so the
// editor can overwrite them in place); anything else is LEVEL_<UPPERCASE>.
// Kept in sync with the save plugin's registration in main.ts.
export function constName(name: string): string {
  const m = /^level(\d+)$/i.exec(name);
  return m ? `LEVEL_${m[1]}` : `LEVEL_${name.toUpperCase()}`;
}

// Emit a `{ ascii, meta }` LevelModule source file (the same shape parseLevel
// accepts). The LevelModule annotation makes the type import "used" under
// noUnusedLocals.
export function emitModule(name: string, model: EditorModel): string {
  const ascii = model.toAscii();
  const meta = formatMeta(model.metaObject());
  return `// Generated by the level editor (src/editor). Safe to hand-edit.
import type { LevelModule } from "../level";

export const ${constName(name)}: LevelModule = {
  ascii: \`
${ascii}
\`,
  meta: ${meta},
};
`;
}

function formatMeta(meta: LevelMeta): string {
  const keys = Object.keys(meta);
  if (keys.length === 0) return "{}";
  const entries = keys.map((k) => {
    const m = meta[k];
    const fields: string[] = [];
    if (m.facing !== undefined) fields.push(`facing: ${JSON.stringify(m.facing)}`);
    if (m.spawner) fields.push(`spawner: true`);
    return `    ${JSON.stringify(k)}: { ${fields.join(", ")} }`;
  });
  return `{\n${entries.join(",\n")},\n  }`;
}
