# Regenerates art-manifest.md: a complete directory of every art/metadata file
# in the import_tiles* folders (and assets/art once it exists).
# Run from anywhere: powershell -File tools/generate-art-manifest.ps1

$root = Split-Path $PSScriptRoot -Parent
$folders = @(Get-ChildItem $root -Directory | Where-Object { $_.Name -like "import_tiles*" -or $_.Name -eq "assets" } | Sort-Object Name)

$out = @()
$out += "# Art Asset Manifest"
$out += ""
$out += "Auto-generated by ``tools/generate-art-manifest.ps1`` on $(Get-Date -Format yyyy-MM-dd)."
$out += "Do not edit by hand - rerun the script after adding, removing, or moving assets."
$out += ""

$totalPng = 0
$totalJson = 0

foreach ($folder in $folders) {
    $files = @(Get-ChildItem $folder.FullName -File -Recurse)
    if ($files.Count -eq 0) { continue }

    $pngs = @($files | Where-Object { $_.Extension -eq ".png" })
    $jsons = @($files | Where-Object { $_.Extension -eq ".json" })
    $totalPng += $pngs.Count
    $totalJson += $jsons.Count

    $out += "## $($folder.Name)/ ($($pngs.Count) PNG, $($jsons.Count) JSON)"
    $out += ""

    $names = @($files | ForEach-Object { $_.BaseName } | Sort-Object -Unique)
    foreach ($name in $names) {
        $exts = @($files | Where-Object { $_.BaseName -eq $name } |
            ForEach-Object { $_.Extension.TrimStart(".") } | Sort-Object)
        $out += "- $name [$($exts -join '+')]"
    }
    $out += ""
}

$out += "---"
$out += "Total: $totalPng PNG, $totalJson JSON"

$manifestPath = Join-Path $root "art-manifest.md"
$out | Set-Content $manifestPath -Encoding UTF8
Write-Output "Wrote $manifestPath ($totalPng PNG, $totalJson JSON)"
